name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Debug secrets
  run: |
    echo "Docker Username: ${{ secrets.DOCKER_USERNAME }}"
    if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then echo "❌ DOCKER_USERNAME is empty"; fi

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t arora_sid/react-test -f Dockerfile.dev .

      - name: Run tests
        run: docker run -e CI=true arora_sid/react-test npm test